# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
# found & used following as inspiration:
#   - https://blog-devops.obiwan.xyz/posts/talos-ha-cluster-with-3-3-nodes-on-proxmox/
#   - https://github.com/bpg/home-ops/blob/1f8f34a17efd69b64355479e3e4471b741efabbd/talos/talconfig.yaml
#   - https://github.com/budimanjojo/talhelper/blob/fb87d9313d1605ef68602881bebf5af8d782eb51/example/talconfig.yaml
#   - https://github.com/bjw-s-labs/home-ops/blob/c4b67b45bf74214ac2363c71cd286b5203990049/kubernetes/talos/talconfig.yaml
---
clusterName: pokemon-gym

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.10.5
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.33.3

endpoint: https://pallet-town.dev.elrey.casa:6443
additionalApiServerCertSans: &sans
  - pallet-town.dev.elrey.casa
  - 127.0.0.1
  - &talosControlplaneVip 172.16.100.99
additionalMachineCertSans: *sans

clusterPodNets: ["10.224.0.0/16"]
clusterSvcNets: ["10.240.0.0/16"]

# Disable built-in CNI to use Cilium (a CNI is required to be marked ready...so comment out if debugging)
# cniConfig:
#   name: none

nodes:
  - hostname: k8s-dev-cp1
    ipAddress: 172.16.100.100
    installDisk: &proxmoxDisk /dev/vda
    controlPlane: true
    nameservers:
      - &internalDmzDns "172.16.100.1"
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: false
        addresses:
          - 172.16.100.100/23
        routes:
          - &internalDmzRoutes
            network: "0.0.0.0/0"
            gateway: "172.16.100.1"
        vip:
          ip: *talosControlplaneVip
  - hostname: "k8s-dev-wr1"
    ipAddress: 172.16.30.5
    installDisk: *proxmoxDisk
    controlPlane: false
    nameservers:
      - &dmzDns 172.16.30.1
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: false
        addresses:
          - 172.16.30.5/24
        routes:
          - &dmzRoutes
            network: "0.0.0.0/0"
            gateway: "172.16.30.1"

# Global patches
patches:
  #   - "@./patches/global/machine-files.yaml"
  #   - "@./patches/global/machine-kubelet.yaml"
  - "@./../shared_patches/global/machine-sysctls.yaml"

# Controller patches
controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
          # from blog
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
  # patches:
  #   - "@./patches/controller/admission-controller-patch.yaml"
  #   - "@./patches/controller/cluster.yaml"

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          # - siderolabs/gasket-driver
          # for proxmox
          - siderolabs/qemu-guest-agent
          # from blog
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
