[project]
name = "homelab"
version = "0.1.0"
description = "IaC homelab"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "ansible-core>=2.18.5",
    "proxmoxer>=2.2.0",
]

[tool.uv]
dev-dependencies = [
    "ansible-lint>=25.4.0",
]
