# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m0s
  timeout: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      version: "v36.3.*"
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    # https://github.com/techno-tim/launchpad/blob/928bed1d961e8e3e34f5ef747cb4f004e34d3895/kubernetes/traefik-cert-manager/traefik/values.yaml
    globalArguments:
      - "--global.sendanonymoususage=false"
      # - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"

    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirections:
          entrypoint:
            to: websecure
            priority: 10
      websecure:
        http3:
          enabled: true
        advertisedPort: 4443
        tls:
          enabled: true

    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        # from MetalLB range: kubectl -n metallb get ipaddresspools.metallb.io -o yaml
        loadBalancerIP: 172.16.30.30
      loadBalancerSourceRanges: []
      externalIPs: []
