apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/namespace.yaml
  - storage-classes/nfs/nfs-storage_class.yaml
  - tailscale/tailscale-secrets.sops.yaml
  - tailscale/tailscale.yaml
  - metallb/metallb.yaml
  - ingress/traefik.yaml
