# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 10m0s
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 10m0s
  timeout: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz-ip-space
  namespace: metallb
spec:
  addresses:
    ## these are CP IPs...
    # - 172.16.100.130-172.16.100.175
    - 172.16.30.30-172.16.30.39
---
# https://notes.joshrnoll.com/notes/deploy-talos-linux-with-local-vip-tailscale-longhorn-metallb-and-traefik/
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - dmz-ip-space
