# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-store
  namespace: storage-nfs
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-client
  namespace: storage-nfs
spec:
  interval: 10m0s
  timeout: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.*"
      sourceRef:
        kind: HelmRepository
        name: nfs-store
  values:
    nfs:
      server: "172.16.20.21"
      path: "/mnt/constraint/k8s_data/prod"
    storageClass:
      create: true
      defaultClass: true
      onDelete: Delete
