# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 10m0s
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m0s
  timeout: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: tailscale-operator
      version: "1.84.*"
      sourceRef:
        kind: HelmRepository
        name: tailscale
  valuesFrom:
    - kind: Secret
      name: tailscale-secrets
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secrets
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
